### ISSUE TITLE
No binary installed anymore

### ISSUE THREAD

**Issue by berkus** [oli-obk/prettydiff#20]
```
cargo install prettydiff --features cli
    Updating crates.io index
error: there is nothing to install in `prettydiff v0.7.0`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency to a Cargo project with `cargo add`.
```

Not sure if this is related to some changes in cargo, seems like prettydiff itself hasn't been updated in a while.

```
$ cargo -V
cargo 1.80.0-nightly (0de7f2ec6 2024-05-17)

$ rustc -V
rustc 1.80.0-nightly (b92758a9a 2024-05-20)
```

**Comment by oli-obk** [comment]
This was removed on purpose in https://github.com/oli-obk/prettydiff/commit/b1de1e7fa14d9faf5db7e7b85b888e355a9253aa and https://github.com/oli-obk/prettydiff/commit/9281f28d83b4451eebd0d9958e2838760b54eac2

I have taken over maintenance of this crate yesterday, and am still catching up. I didn't know it used to have a binary, and I have no use for a binary myself, so I won't be adding or maintaining one. Though it should be easy to pull out the existing binary into its own crate that depends on this one.

**Comment by romankoblov** [comment]
Issue was with some CVE in structopt, cli util was pretty useless (didn't use it myself, just example how to use API). Package itself was failed attempt to make diff for PTX asm more structured, all diff algorithms for string very basic and not performant (it is just implementation basic algorithm from wiki). Not sure why people use this, but thank you for taking over maintance.
